### ISSUE TITLE
The encoding used to store pyon files is system-dependent

### ISSUE THREAD

**Issue by pmldrmota** [m-labs/sipyco#13]
### One-Line Summary
`pyon.store_file` uses the operating system's default encoding, which does not guarantee support for non-ASCII characters.

### Actual behavior
On some systems, the default encoding does not include commonly used symbols, such as greek letters.
`UnicodeEncodeError: 'charmap' codex can't encode character '\u03c0' in position 1234: character maps to <undefined>`

### Suggested solution
Specify the encoding, for example `utf-8`:
```python
def store_file(filename, x):
    """Encodes a Python object and writes it to the specified file."""
    contents = encode(x, True)
    directory = os.path.abspath(os.path.dirname(filename))
    with tempfile.NamedTemporaryFile("w", dir=directory, delete=False, encoding='utf-8') as f:
        f.write(contents)
        f.write("\n")
        tmpname = f.name
    os.replace(tmpname, filename)

def load_file(filename):
    """Parses the specified file and returns the decoded Python object."""
    with open(filename, "r", encoding='utf-8') as f:
        return decode(f.read())````

**Comment by pmldrmota** [comment]
From the documentation:

> Each object is serialized on a single line, **with only ASCII characters**.

I don't see why this would be a feature?

**Comment by dnadlinger** [comment]
Fixed in https://github.com/m-labs/sipyco/commit/13dc45823e14a62854d89eda1d33ce0f7f7c8569, even before the issue was opened. That's time travel for you!

**Comment by dnadlinger** [comment]
To be clear, this just brings certain Windows builds/environments in line with what the behaviour already was on other platforms. If we really want ASCII-only output, we'll need to encode all strings at a higher level.
