### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by Hanros94** [m-labs/sipyco#14]
Hi

I have a very basic question, how do you install this as an addition to an existing ARTIQ version?

**Comment by systemofapwne** [comment]
For a bare install, I did this.
```
git clone https://github.com/m-labs/sipyco.git
cd sipyco && pip install .
```
Should also work with an already set up Artiq system

**Comment by sbourdeauducq** [comment]
``artiq-full.sipyco`` with Nix, or if you are using Windoze, ``conda install sipyco``. As mentioned it's also an ARTIQ dependency and should be already installed if you installed ARTIQ.

**Comment by LargeDumpling** [comment]
> I use with pip
> 
> pip install git+https://github.com/m-labs/sipyco
> or this inside `pyproject.toml`
> 
> dependencies = [
>   "sipyco @ git+https://github.com/m-labs/sipyco",
> ]

Thanks, the first command works well on my computer.
