### ISSUE TITLE
Update package on Nix/Conda

### ISSUE THREAD

**Issue by lriesebos** [m-labs/sipyco#18]
@sbourdeauducq the sipyco package on Nix/Conda seems to be fairly outdated (over a year). See https://git.m-labs.hk/M-Labs/nix-scripts/src/branch/master/artiq-fast/pkgs/python-deps.nix . Would be great if sipyco could be bumped to v1.2 and updated accordingly in the nix-scripts.

**Comment by sbourdeauducq** [comment]
done
